#!/bin/bash

echo "Installing Requirements...\n"

sudo pacman -S xorg xorg-xinit xorg-xrandr base-devel rofi alacritty bluez bluez-utils bluetui \
firefox brightnessctl ttf-jetbrains-mono-nerd picom fish starship \
thunar neovim obsidian xpdf feh shotgun udisks2 obsidian xpdf unzip power-profiles-daemon yt-dlp jq

sudo systemctl enable --now bluetooth.service 

mkdir ~/.install
mkdir ~/.scripts
mkdir ~/Downloads
mkdir ~/Documents
mkdir ~/Videos
mkdir ~/Pictures

sleep 2
echo "Coping configs...\n"
cp -r ./Configs/* ~/.config

echo "Coping Home Files...\n"
cp ./Home/* ~/.

echo "Coping Scripts...\n"
cp ./Scripts/* ~/.scripts

sudo chmod +x ~/.scripts/autostart.sh
sudo chmod +x ~/.scripts/volume.sh
sudo chmod +x ~/.scripts/brightness.sh
sudo chmod +x ~/.scripts/PPD.sh
sudo chmod +x ~/.scripts/ppd-watcher
sudo chmod +x ~/.scripts/sb-powerprofiles
sudo chmod +x ~/.scripts/battery
sudo chmod +x ~/.scripts/dwm-cheatsheet
sudo chmod +x ~/.scripts/sb-weather

echo "DWM & DWMBLOCKS...\n"

cp -r ./Installs/dwm ~/.install
cp -r ./Installs/dwmblocks ~/.install

cd ~/.install/dwm
sudo make clean install

echo "DWM Complete...\n"
sleep 2

cd ~/.install/dwmblocks
sudo make clean install

echo "DWMBLOCKS Complete...\n"
echo "Script is done...\n"
