#!/bin/bash

echo "Installing Requirements...\n"

sudo pacman -S xorg xorg-xinit xorg-xrandr base-devel rofi alacritty bluez bluez-utils bluetui \
firefox brightnessctl ttf-jetbrains-mono-nerd picom fish starship \
thunar helix neovim obsidian xpdf feh shotgun udisks2 obsidian xpdf unzip power-profiles-daemon yt-dlp

sudo systemctl enable --now bluetooth.service 

mkdir ~/.install
mkdir ~/.scripts

sleep 2
echo "Coping configs...\n"
cp -r ./Configs/* ~/.config

cp ./Home/* ~/.

cp ./Scripts/* ~/.scripts

sudo chmod +x ~/.scripts/autostart.sh
sudo chmod +x ~/.scripts/volume.sh
sudo chmod +x ~/.scripts/brightness.sh
sudo chmod +x ~/.scripts/PPD.sh
sudo chmod +x ~/.scripts/ppd-watcher
sudo chmod +x ~/.scripts/sb-powerprofiles
sudo chmod +x ~/.scripts/battery

echo "DWM & DWMBLOCKS...\n"

cp -r ./Installs/dwm ~/.install
cp -r ./Installs/dwmblocks ~/.install

cd ~/.install/dwm
sudo make clean install

echo "DWM Complete...\n"
sleep 2

cd ~/.install/dwmblocks
sudo make clean install

echo "DWMBLOCKS Complete...\n"
echo "Script is done...\n"
