#!/bin/sh
# ~/.scripts/ppd-watcher

dbus-monitor --system \
    "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/org/freedesktop/UPower/PowerProfiles'" \
    "type='signal',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',path='/net/hadess/PowerProfiles'" \
| while read -r line; do
    case "$line" in
        *ActiveProfile*|*member=PropertiesChanged*)
            pkill -RTMIN+13 dwmblocks
            ;;
    esac
done
